/* This file was generated by a script using the mld_base_prec_type.F90 file as a basis. */
#ifndef MLD_CONST_H_
#define MLD_CONST_H_
#ifdef __cplusplus
extern "C" { 
#endif
#define MLD_VERSION_STRING_ ( "2.3.0" )
#define MLD_VERSION_MAJOR_ ( 2 )
#define MLD_VERSION_MINOR_ ( 3 )
#define MLD_PATCHLEVEL_ ( 0 )
#ifdef __cplusplus
}
#endif
#endif
